name: Deployment for staging
on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        env:
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_CONFIG" > ~/.ssh/config
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Configure
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
          LOG_HANDLER_LOG_DIR: ${{ secrets.LOG_HANDLER_LOG_DIR }}
          DB_HANDLER_MONGO_HOST: ${{ secrets.DB_HANDLER_MONGO_HOST }}
          DB_HANDLER_MONGO_PORT: ${{ secrets.DB_HANDLER_MONGO_PORT }}
          DB_HANDLER_MONGO_DB_NAME: ${{ secrets.DB_HANDLER_MONGO_DB_NAME }}
          DB_HANDLER_MONGO_ARTICLE_COLLECTION_NAME: ${{ secrets.DB_HANDLER_MONGO_ARTICLE_COLLECTION_NAME }}
          DB_HANDLER_MONGO_TWEET_COLLECTION_NAME: ${{ secrets.DB_HANDLER_MONGO_TWEET_COLLECTION_NAME }}
          DB_HANDLER_ES_HOST: ${{ secrets.DB_HANDLER_ES_HOST }}
          DB_HANDLER_ES_PORT: ${{ secrets.DB_HANDLER_ES_PORT }}
          TWITTER_HANDLER_OAUTH_TOKEN: ${{ secrets.TWITTER_HANDLER_OAUTH_TOKEN }}
          TWITTER_HANDLER_OAUTH_TOKEN_SECRET: ${{ secrets.TWITTER_HANDLER_OAUTH_TOKEN_SECRET }}
          TWITTER_HANDLER_OAUTH_CONSUMER_KEY: ${{ secrets.TWITTER_HANDLER_OAUTH_CONSUMER_KEY }}
          TWITTER_HANDLER_OAUTH_CONSUMER_SECRET: ${{ secrets.TWITTER_HANDLER_OAUTH_CONSUMER_SECRET }}
          SLACK_HANDLER_ACCESS_TOKENS: ${{ secrets.SLACK_HANDLER_ACCESS_TOKENS }}
          SLACK_HANDLER_APP_CHANNELS: ${{ secrets.SLACK_HANDLER_APP_CHANNELS }}
          ARTICLE_LIST: ${{ secrets.ARTICLE_LIST }}
          TWEET_LIST: ${{ secrets.TWEET_LIST }}
          SITE_LIST: ${{ secrets.SITE_LIST }}
        run: |
          python conf.py
      - name: Deploy to server
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH_STAGING }}
          REMOTE: ${{ secrets.REMOTE }}
        run: |
          chmod -R g+w .
          rsync -av --exclude 'data/' . $REMOTE:$DEPLOY_PATH
